// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using One_to_One.Models;

#nullable disable

namespace One_to_One.Migrations
{
    [DbContext(typeof(DbcontextOne))]
    partial class DbcontextOneModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("One_to_One.Models.AdharDeatails", b =>
                {
                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<long>("AdharNumber")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeId");

                    b.ToTable("AdharDeatails");
                });

            modelBuilder.Entity("One_to_One.Models.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeId"));

                    b.Property<string>("EmployeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("One_to_One.Models.AdharDeatails", b =>
                {
                    b.HasOne("One_to_One.Models.Employe", "Employe")
                        .WithOne("AdharDeatails")
                        .HasForeignKey("One_to_One.Models.AdharDeatails", "EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("One_to_One.Models.Employe", b =>
                {
                    b.Navigation("AdharDeatails");
                });
#pragma warning restore 612, 618
        }
    }
}
